unbind C-a
set-option -g prefix C-w

bind d split-window -h -c "#{pane_current_path}"
bind f split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

set -g mouse on

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#colors:
#Background: #191724
#Color:      #6e6a86

# panes
set -g pane-border-style 'fg=#191424'
set -g pane-active-border-style 'fg=#6e6a86'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=#191424 fg=#6e6a86'
set -g status-left ''
set -g status-right ''
set -g status-left-length 20
set -g status-right-length 0

setw -g window-status-current-style 'bg=#6e6a86 fg=#191424 bold'
setw -g window-status-current-format '#[fg=#191424]#I #[fg=#232634]#W '

setw -g window-status-style 'fg=#6e6a86 bg=#191424'
setw -g window-status-format '#[fg=#6e6a86]#I #[fg=#bac2de]#W '


set-option -as terminal-features ",xterm-256color:RGB""

# messages
set -g message-style 'fg=#6e6a86 bg=#191424 bold'

set -sg escape-time 0
set-option -g focus-events on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
