window.padding.x = 5
window.padding.y = 2
 
scrolling.history = 10000
scrolling.multiplier = 3

window.opacity = 0.95
#window.blur = true

window.decorations = "None"

font.normal = { family = "Hack Nerd Font Mono"}
font.size = 12
font.offset.y = 4
font.glyph_offset.y = 2


mouse.hide_when_typing = false

# Default colors
colors.primary.background = "#1c1c1c"
colors.primary.foreground= '0xe0def4'

# Colors the cursor will use if `custom_cursor_colors` is true
colors.cursor.text= '0xe0def4'
colors.cursor.cursor= '0xe0def4'

# Normal colors
[colors.normal]
black=   '0x1f1d2e'
red=     '0xeb6f92'
green=   '0x9ccfd8'
yellow=  '0xf6c177'
blue=    '0x31748f'
magenta= '0xc4a7e7'
cyan=    '0x9ccfd8'
white=   '0xe0def4'

[colors.bright]
black=   '0x908caa'
red=     '0xeb6f92'
green=   '0x9ccfd8'
yellow=  '0xf6c177'
blue=    '0x31748f'
magenta= '0xc4a7e7'
cyan=    '0x9ccfd8'
white=   '0xe0def4'



